# Generated by Django 2.2.1 on 2019-05-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=15)),
                ('beschreibung', models.TextField(max_length=160)),
                ('tag', models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five'), (6, 'six'), (7, 'seven'), (8, 'eight'), (9, 'nine'), (10, 'ten'), (11, 'eleven'), (12, 'twelve'), (13, 'thirteen'), (14, 'fourteen'), (15, 'fifteen'), (16, 'sixteen'), (17, 'seventeen'), (18, 'eighteen'), (19, 'nineteen'), (20, 'twenty'), (21, 'twenty-one'), (22, 'twenty-two'), (23, 'twenty-three'), (24, 'twenty-four'), (25, 'twenty-five'), (26, 'twenty-six'), (27, 'twenty-seven'), (28, 'twenty-eight'), (29, 'twenty-nine'), (30, 'thirty'), (31, 'thirty-one')])),
                ('monat', models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five'), (6, 'six'), (7, 'seven'), (8, 'eight'), (9, 'nine'), (10, 'ten'), (11, 'eleven'), (12, 'twelve')])),
                ('jahr', models.IntegerField(choices=[(2019, 'two-thousand-nineteen'), (2020, 'two-thousand-twenty'), (2021, 'two-thousand-twenty-one'), (2022, 'two-thousand-twenty-two'), (2023, 'two-thousand-twenty-three'), (2024, 'two-thousand-twenty-four'), (2025, 'two-thousand-twenty-five'), (2026, 'two-thousand-twenty-six'), (2027, 'two-thousand-twenty-seven'), (2028, 'two-thousand-twenty-eight'), (2029, 'two-thousand-twenty-nine')])),
                ('status', models.IntegerField()),
            ],
        ),
    ]
